name: RedHorizon - Book Spotlight
on:
  schedule:
    - cron: "0 18 * * 1,3,5"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    concurrency: redhorizon-book-spotlight
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run book spotlight
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
        run: |
          python -c "from src.tasks import run_book_spotlight; print(run_book_spotlight())"
      - name: Commit state
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "redhorizon-bot"
          git add data/*.json
          git diff --staged --quiet || git commit -m "Update state [book-spotlight]"
          git push
