name: Daily Image

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"  # 12:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show UTC time (debug)
        run: date -u
      - name: Run daily image task
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
        run: |
          python - << 'PY'
          from src.tasks import run_daily_image
          print(run_daily_image())
          PY
      - name: Persist state (image caches)
        run: |
          git config user.name  "redhorizon-bot"
          git config user.email "bot@example.com"
          git add data/image_cache.json data/seen_links.json || true
          git commit -m "chore: update image cache [skip ci]" || echo "no changes"
          git push || true
