name: RedHorizon - LAUNCH REMINDERS (10m)

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    concurrency: redhorizon-launch-reminders

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run reminders (T-24h / T-1h)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python - << 'PY'
          from src.tasks import run_launch_reminders
          print(run_launch_reminders())
          PY

      - name: Commit reminder flags
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "redhorizon-bot"
          git add data/launch_cache.json
          git diff --staged --quiet || git commit -m "Update launch cache [reminders]"
          git push
