name: RedHorizon - Terraforming Update
on:
  schedule:
    - cron: "0 18 * * 4"  # Thursday 18:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    concurrency: redhorizon-terraforming
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run terraforming update
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
        run: |
          python -c "from src.tasks import run_terraforming_post; print(run_terraforming_post())"
      - name: Commit state
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "redhorizon-bot"
          git add data/*.json
          git diff --staged --quiet || git commit -m "Update state [terraforming-post]"
          git push
