name: Trending Pulse

on:
  schedule:
    # Runs at :05, :20, :35, :50 (UTC). Offset from Breaking to avoid overlap.
    - cron: "5,20,35,50 * * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: trending-pulse
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run Trending Pulse
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
        run: python -c "from src.tasks import run_trending_pulse; print(run_trending_pulse())"
